
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgsnxjdcmzezvvkzhddi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnc254amRjbXplenZ2a3poZGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjE5NDksImV4cCI6MjA1Nzg5Nzk0OX0.SRUJf7_W2Y3TZpCruQojPMkCDQyd8pzRw5a7cfO0WVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to create a new user and set their role
export const createUser = async (
  email: string, 
  password: string, 
  role: 'admin' | 'editor'
) => {
  // Create the user in Supabase Auth
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });

  if (error) {
    throw error;
  }

  // If the user was created successfully, update their role in profiles
  if (data.user) {
    const { error: profileError } = await supabase
      .from('profiles')
      .update({ role })
      .eq('id', data.user.id);

    if (profileError) {
      console.error("Error setting user role:", profileError);
      // We don't throw here as the user was created successfully
    }
  }

  return { data, error };
};
